version: '2.0'

services:
  api:
    build: ./back
    image: reimbursinator_back
    command: gunicorn --bind 0.0.0.0:444 --keyfile /etc/ssl/private/selfsigned.key --certfile /etc/ssl/private/selfsigned.crt reimbursinator.wsgi:application 
    #volumes:
    #  - ./app/:/usr/src/back/
    ports:
      - "8444:444"
    environment:
      - SECRET_KEY=please_change
  web:
    build: ./front
    image: reimbursinator_front
    ports:
      - "8443:443"
    environment:
      - NGINX_HOST=reimbursinator.com
      - NGINX_PORT=443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
